### ISSUE TITLE
Cannot Submit Form -

### ISSUE THREAD

**Issue by artistro08** [mplodowski/formbuilder-plugin-public#3]
**Describe the bug**
I cannot submit the form via the pages plugin snippet

**To Reproduce**
Add form to static page via snippet
Submit the form

**Expected behavior**
The Form Submitted and I get a log in the backend 

**October version**
October 2.1.20

**Plugin version**
2.0.1

**Additional context**
Here's the stack trace 

```
ErrorException: Trying to access array offset on value of type null in /home/artistro08/.sites/procedural-tech/plugins/renatio/formbuilder/traits/RenderFormAjax.php:143
Stack trace:
#0 /home/artistro08/.sites/procedural-tech/plugins/renatio/formbuilder/traits/RenderFormAjax.php(143): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/artistro08/.sites/procedural-tech/plugins/renatio/formbuilder/traits/RenderFormAjax.php(109): Renatio\FormBuilder\Components\RenderForm->checkFileRequired()
#2 /home/artistro08/.sites/procedural-tech/plugins/renatio/formbuilder/traits/RenderFormAjax.php(32): Renatio\FormBuilder\Components\RenderForm->makeValidator()
#3 /home/artistro08/.sites/procedural-tech/modules/cms/classes/ComponentBase.php(187): Renatio\FormBuilder\Components\RenderForm->onSubmit()
#4 /home/artistro08/.sites/procedural-tech/modules/cms/classes/Controller.php(874): Cms\Classes\ComponentBase->runAjaxHandler()
#5 /home/artistro08/.sites/procedural-tech/modules/cms/classes/Controller.php(739): Cms\Classes\Controller->runAjaxHandler()
#6 /home/artistro08/.sites/procedural-tech/modules/cms/classes/Controller.php(375): Cms\Classes\Controller->execAjaxHandlers()
#7 /home/artistro08/.sites/procedural-tech/modules/cms/classes/Controller.php(222): Cms\Classes\Controller->runPage()
#8 /home/artistro08/.sites/procedural-tech/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run()
#9 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Cms\Classes\CmsController->run()
#10 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#11 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch()
#12 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#13 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#14 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#15 /home/artistro08/.sites/procedural-tech/plugins/rainlab/translate/classes/LocaleMiddleware.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): RainLab\Translate\Classes\LocaleMiddleware->handle()
#17 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#19 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#21 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle()
#23 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#25 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#27 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then()
#29 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack()
#30 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute()
#31 /home/artistro08/.sites/procedural-tech/vendor/october/rain/src/Router/CoreRouter.php(31): Illuminate\Routing\Router->dispatchToRoute()
#32 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\Rain\Router\CoreRouter->dispatch()
#33 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#34 /home/artistro08/.sites/procedural-tech/plugins/offline/responsiveimages/classes/ResponsiveImagesMiddleware.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): OFFLINE\ResponsiveImages\Classes\ResponsiveImagesMiddleware->handle()
#36 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /home/artistro08/.sites/procedural-tech/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#38 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#39 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then()
#41 /home/artistro08/.sites/procedural-tech/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#42 /home/artistro08/.sites/procedural-tech/index.php(43): Illuminate\Foundation\Http\Kernel->handle()
#43 /home/artistro08/.config/composer/vendor/cpriego/valet-linux/server.php(232): require('/home/artistro0...')
#44 {main}
```

**Comment by artistro08** [comment]
Absolultely my fault. Was on the wrong version Closing
